class MapperIndex:
    DATE_INDEX = 0
    DATA_TO_SKIP = 1
    MAX_TEMPERATURE = 1
    YEAR_IN_FILE_NAME = 2
    MIN_TEMPERATURE = 3
    MAX_HUMIDITY = 8
    MAX_OPERATION_STRING = 'max'
    MIN_OPERATION_STRING = 'min'

