class MapperIndex:
    DATE_INDEX = 0
    DATA_TO_SKIP = 1
    MAX_TEMPERATURE = 1
    ARGUMENT_FILE_PATH_INDEX = 1
    ARGUMENT_SWITCH_INDEX = 2
    ARGUMENT_YEAR_INDEX = 3
    MAX_INPUT_ARGUMENT_LENGTH = 4
    YEAR_IN_FILE_NAME = 2
    MIN_TEMPERATURE = 3
    MAX_HUMIDITY = 8
    MAX_OPERATION_STRING = 'max'
    MIN_OPERATION_STRING = 'min'
    YEARLY_CALCULATION_SWITCH = '-e'
    All_YEAR_CALCULATION_SWITCH = '-a'

